### ISSUE TITLE
Use different color for XML attributes

### ISSUE THREAD

**Issue by 0jrp0** [pedropenna/Intellij-Zenburn#5]
XML attributes are being highlighted in blue. Consider using a better color that contrasts well with the overall theme.

**Comment by pedropenna** [comment]
I couldn't reproduce this issue either, so here's what I did instead on (https://github.com/pedropenna/Intellij-Zenburn/commit/4f74a8da3518df6120bea39a52b794be93b0f606):
- I changed the only purple text that I could find. It was on the "Groovy instance property reference"
- I also changed the "Groovy unresolved value" that used to be a dull dark gray.
- The HTML and XML tags were darkened a bit for better contrast between the tag brackets and normal text. I know, nobody asked for that but I changed it anyway because it's much easier on the eyes :)

And... When you say "highlighting", do you mean the background color when the text is selected or just the XML attributes?

**Comment by 0jrp0** [comment]
I meant actually the foreground colors. This may also be related to the other bug I filed about enums. There may be something else in my custom build that is conflicting with the configuration. I could try to reimport the colors again and see if these values are getting updated from somewhere else...
